### ISSUE TITLE
Can't manage to start the app properly on localhost

### ISSUE THREAD

**Issue by Andream98** [markstory/docket-app#29]
I'm trying to convert a new CakePHP 4 project (using the InertiaJS adapter from @ishanvyas22) from webpack+vue2.6 to vite+vue3, so I decided to look at this project to get a grasp of how to do it.

I've followed the installation guide, but I'm unable to run the app on my PC. When I run the server.js script, which starts both the CakePHP and vite servers, and then navigate to localhost:3000 I see these errors in the browser:
![image](https://user-images.githubusercontent.com/52160332/149643791-8ebce342-c40c-4a47-9d31-9a289ca73c4b.png)

Is there any extra configuration that I've missed? Also, did you follow any guide to swap webpack out for vite?

**Comment by markstory** [comment]
> Is there any extra configuration that I've missed?

I don't think so. Those errors look like they are all coming from vite. Are there any errors shown in the stdout of `bin/ server.js`

> Also, did you follow any guide to swap webpack out for vite?

No, it was pretty simple as my webpack configuration was very small. Instead of trying to migrate -I started over when I went to vite.

**Comment by Andream98** [comment]
Thank you for your reply!

> I don't think so. Those errors look like they are all coming from vite. Are there any errors shown in the stdout of bin/ server.js

I mean, not that I can see. Here is a screenshot of the log that it spits out when I connect to any page:

![Screenshot from 2022-01-16 12-33-58](https://user-images.githubusercontent.com/52160332/149658166-384eb46f-d85d-49f3-a89e-0e212074d79d.png)

And in my error.log i get one of these for each of the files that are not found:

`

2022-01-16 11:37:34 error: [Cake\Routing\Exception\MissingRouteException] A route matching "/@vite/client" could not be found. in /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Routing/RouteCollection.php on line 197
Exception Attributes: array (
  'url' => '/@vite/client',
)
Stack Trace:
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Routing/Router.php:232
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:139
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:126
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php:60
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /home/andrea/PhpstormProjects/docket-app/vendor/cakephp/cakephp/src/Http/Server.php:90
- /home/andrea/PhpstormProjects/docket-app/webroot/index.php:40

Request URL: /@vite/client
Referer URL: http://localhost:3000/users/add`

> No, it was pretty simple as my webpack configuration was very small. Instead of trying to migrate -I started over when I went to vite.

So you started out with a setup similar to mine, meaning you followed the installation guide for the Inertia.js adapter for CakePHP?

**Comment by markstory** [comment]
The errors for vite paths sound like vite devserver isn't running properly. Are you able to use yarn build to get static assets? If the docket is not in debug mode it expects precompiled assets to exist already.

**Comment by Andream98** [comment]
Yes, yarn build succeeds without any error. And I've also tried to load the generated static assets, and they work. But for some reason as I use yarn build, it stays in debug mode so to load them I had to edit the frontend_assets.php like this:

![image](https://user-images.githubusercontent.com/52160332/149681821-931b7b0f-f12b-459f-9a4c-70865cfdc751.png)

**Comment by markstory** [comment]
Debugkit hitting a 500 and the 400s for port 3000 look like the souce of the problem. I don't run into those locally. I can try from a fresh install though.

**Comment by markstory** [comment]
I tried again tonight with a fresh install, and while the first run wasn't slick, I did end up with a working environment after calling `yarn build` and then restarting `node bin/server.js`. I didn't run into the same errors with port 3000 that you did.

**Comment by Andream98** [comment]
Ok so it is looking like an environment problem. Thanks for your help!
I will try to understand the root of the problem and will share more if I find anything that might be useful for others. Feel free to close this issue as it is not a project problem.

**Comment by Andream98** [comment]
Found out what the problem was (me) :D

I always opened the project from http://localhost:3000, but now I tried to open it from http://localhost:8765 and everything is working fine!
